package br.com.uisa.externalrepair.application.domain.model;

public enum StatusName {
    INICIO_REPARO,
    ENTRADA_RECEBIDA,
    NEGOCIACAO_IBID,
    ANDAMENTO_REPARO,
    ANALISE_FISCAL,
    DEFINICAO_TRANSPORTE,
    ENTRADA_ESTOQUE,
    RETORNO_FATURAMENTO,
    AVALIACAO_TECNICA,
    APROVACAO_GESTOR,
    RETORNO_FISCAL,
    VALIDACAO_VENDA,
    LAUDO_DESCARTE,
    RETORNO_TRANSPORTE,
    ESTOQUE_FINAL,
    PROPOSTA_COMERCIAL,
    ANALISE_PROPOSTA,
    INTEGRACAO_BPM,
    FINALIZADO
}
