export const PERMISSIONS = {
  FISCAL: {
    canEdit: ['fiscal'],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  WAREHOUSE_AGRICOLA: {
    canEdit: ['almoxarifado'],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  WAREHOUSE_INDUSTRIAL: {
    canEdit: ['almoxarifado'],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  WAREHOUSE_ASSARI: {
    canEdit: ['almoxarifado'],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  LOGISTIC_AGRICOLA: {
    canEdit: ['logistica'],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  LOGISTIC_INDUSTRIAL: {
    canEdit: ['logistica'],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  LOGISTIC_ASSARI: {
    canEdit: ['logistica'],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  ADMIN: {
    canEdit: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  TECHNICAL_MANAGER: {
    canEdit: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canView: [
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
    canAccess: [
      'home',
      'fiscal',
      'almoxarifado',
      'logistica',
      'manutencao',
      'recebimento',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  COUNTERPARTY: {
    canEdit: ['manutencao', 'contraparte', 'gestortecnico'],
    canView: ['manutencao', 'historico', 'contraparte', 'gestortecnico'],
    canAccess: [
      'home',
      'manutencao',
      'historico',
      'contraparte',
      'gestortecnico',
    ],
  },
  SUPPLIER: {
    canEdit: ['manutencao', 'recebimento'],
    canView: ['manutencao', 'recebimento', 'historico'],
    canAccess: ['home', 'manutencao', 'recebimento', 'historico'],
  },
};

export type PermissionType = keyof typeof PERMISSIONS;
export type SectionType =
  | 'home'
  | 'fiscal'
  | 'almoxarifado'
  | 'logistica'
  | 'manutencao'
  | 'recebimento'
  | 'historico'
  | 'contraparte'
  | 'gestortecnico';
