export enum Routes {
  NOT_FOUND = '*',
  HOME = '/home',
  LOGIN = '/login',
  DEMO = '/demo',
  RECEBIMENTO_HOME = '/recebimento',
  RECEBIMENTO_ITEM = '/recebimento/@item',
  MANUTENCAO = '/manutencao',
  FISCAL = '/fiscal',
  FISCAL_ITEM = '/fiscal/@item',
  FISCAL_PARTIAL = '/fiscal/partial/@item',
  ALMOXARIFADO = '/almoxarifado',
  ALMOXARIFADO_ITEM = '/almoxarifado/@item',
  LOGISTICA = '/logistica',
  LOGISTICA_ITEM = '/logistica/@item',
  CONTRAPARTE = '/contraparte',
  CONTRAPARTE_ITEM = '/contraparte/@item',
  GESTORTECNICO = '/gestortecnico',
  GESTORTECNICO_ITEM = '/gestortecnico/@item',
  HISTORICO = '/historico',
  HISTORICO_ITEM = '/historico/@item',
  MANUTENCAO_ITEM = '/manutencao/@item',
  CODIGO_DE_CONDUTA = '/codigo-de-conduta',
  CONTATO = '/contato',
}
